### ISSUE TITLE
Failure to Fail Over When Sharing IP With Control-Plane and Service

### ISSUE THREAD

**Issue by erismaster** [kube-vip/kube-vip#947] opened 2024-09-16 19:42 UTC
**Describe the bug**
When deploying a cluster and using kube-vip for the control plane, in addition to configuring a service to use the same IP (ingress in this case, on different ports), leader election occurs for both the control plane and the service, which can result in 2 different nodes owning the lease, and thus advertising the IP on the network, causing a lot of dropped requests because kube-vip is only actually responding on one of them. 

**To Reproduce**
1. Deploy a cluster with kube-vip being used for the control plane
2. Deploy a ingress controller and set the necessary settings to have it use the same IP (but again, different ports, 80/443 here)
3. Reboot nodes to trigger failover/lease election and observe that sometimes node A will have the control plane lease, and node B will have the service lease. This leads to 2 nodes on the network advertising the IP and dropped traffic. 

**Expected behavior**
If the IP of a service and the control plane configuration are the same, then only 1 leader election/lease should take place, to ensure that the IP is not advertised across multiple nodes. In other words, if control plane and service are using the same IP, then they should both use the vip_leasename lease "plndr-cp-lock". 

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 24.04
 - Kubernetes Version: v1.28.9
 - Kube-vip Version: v0.8.2

**`Kube-vip.yaml`:**
```yaml
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: lb_enable
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: svc_election
      value: "false"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "15"
    - name: vip_renewdeadline
      value: "10"
    - name: vip_retryperiod
      value: "2"
    - name: address
      value: 10.220.75.199
    - name: prometheus_server
      value: :2112
    image: myregistry.registry.svc.cluster.local:5000/images/kube-vip:v0.8.2
 ```
 
 The service
 ```yaml
   metadata:
    annotations:
      kube-vip.io/loadbalancerIPs: 10.220.75.199
      kube-vip.io/vipHost: management-edar4-jtwnk-wwxgt
      meta.helm.sh/release-name: istio-ingressgateway
      meta.helm.sh/release-namespace: istio-ingress
    creationTimestamp: "2024-09-16T17:51:06Z"
    labels:
      app: istio-ingressgateway
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: istio-ingressgateway
      app.kubernetes.io/version: 1.0.0
      helm.sh/chart: istio-gateway-1.22.2-2
      helm.toolkit.fluxcd.io/name: istio-ingressgateway
      helm.toolkit.fluxcd.io/namespace: my-platform
      implementation: kube-vip
      ipam-address: 10.220.75.199
      istio: ingressgateway
    name: istio-ingressgateway
    namespace: istio-ingress
    resourceVersion: "10235"
    uid: a9c7f6e9-f139-41d7-9a05-5d6a2a33ec8d
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 100.65.199.75
    clusterIPs:
    - 100.65.199.75
    externalTrafficPolicy: Local
    healthCheckNodePort: 31530
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-alt
      nodePort: 30450
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: status-port
      nodePort: 31685
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      nodePort: 31467
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 31349
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: istio-ingressgateway
      istio: ingressgateway
    sessionAffinity: None
    type: LoadBalancer
 ```

**Comment by Cellebyte** [comment] 2024-11-06 07:48
Duplicate of #665

**Closed by Cellebyte** 2024-11-06 07:48 UTC
Labels: duplicate

**Comment by Cellebyte** [comment] 2024-11-06 09:08
Duplicate of #464
