### ISSUE TITLE
External IP not attached to loadbalancer when `externalTrafficPolicy: Local` [0.6.2]

### ISSUE THREAD

**Issue by starizard** [kube-vip/kube-vip#608] opened 2023-09-05 10:38 UTC
**Describe the bug**

When `svc_election: true` and `externalTrafficPolicy: Local` is set, the loadbalancer IP remains Pending

**To Reproduce**
1. Generate Manifest using: 
```
kube-vip manifest daemonset \
    --interface ens160 --taint --inCluster \
    --address 10.255.3.250 \
    --controlplane \
    --services \
    --arp \
    --servicesElection \
    --leaderElection 
```
3. create a service with `externalTrafficPolicy: Local`
4. Loadbalancer's external IP remains Pending

**Expected behavior**
Expect the IP to be provisioned

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1]
 - Kubernetes Version: [e.g. v1.23.15]
 - Kube-vip Version: [e.g. 0.6.2]

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.6.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.6.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: _VIPINTERFACE_
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: svc_election
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: _VIPADDRESS_
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /etc/kubernetes/admin.conf
          name: kubeconfig
      hostAliases:
      - hostnames:
        - kubernetes
        ip: 127.0.0.1
      hostNetwork: true
      serviceAccountName: kube-vip
      volumes:
      - hostPath:
          path: /etc/kubernetes/admin.conf
        name: kubeconfig
  updateStrategy: {}

```
**Additional context**

Couldn't find documentation on this, but will svc_election work when the NodeAffinity restricts kube-vip to master pods only?

**Comment by starizard** [comment] 2023-09-05 11:49
logs of the vip provider:

```
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.087311       1 loadBalancer.go:91] syncing service 'syslog-lb' (7601dd42-9775-4c00-8201-e95b765829a9)
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.090749       1 loadBalancer.go:244] no cidr config for namespace [default] exists in key [cidr-default] configmap [kubevip]
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.090762       1 loadBalancer.go:249] Taking address from [cidr-global] pool
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.097091       1 loadBalancer.go:206] Updating service [syslog-lb], with load balancer IPAM address [10.255.3.187]
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.102091       1 event.go:294] "Event occurred" object="default/syslog-lb" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="LoadbalancerIP" message=" -> 10.255.3.187"
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.103481       1 loadBalancer.go:91] syncing service 'syslog-lb' (7601dd42-9775-4c00-8201-e95b765829a9)
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.103607       1 event.go:294] "Event occurred" object="default/syslog-lb" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.103627       1 event.go:294] "Event occurred" object="default/syslog-lb" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
kube-vip-cloud-provider-95fbf996-zdxbp kube-vip-cloud-provider I0905 11:33:26.103685       1 event.go:294] "Event occurred" object="default/syslog-lb" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"

```

**Comment by d-uzlov** [comment] 2023-09-24 02:03
I'm not sure if cloud controller manager logs are relevant here.
IP does get assigned to the service, I can see the correct `kube-vip.io/loadbalancerIPs` annotation on the service, so I don't think there are any issues in the CCM.

But `spec.loadBalancerIP` and `spec.status.loadBalancer.ingress.[].ip` fields are never updated.
When looking at the kube-vip daemonset logs I can see that all pods are `watching for service`, and that's it.

```
time="2023-09-24T01:23:38Z" level=info msg="Starting kube-vip.io [v0.5.12]"
time="2023-09-24T01:23:38Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[false], Services:[true]"
time="2023-09-24T01:23:38Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2023-09-24T01:23:38Z" level=info msg="prometheus HTTP server started"
time="2023-09-24T01:23:38Z" level=info msg="kube-vip will bind to interface [eth0]"
time="2023-09-24T01:23:38Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2023-09-24T01:23:38Z" level=info msg="beginning watching services, leaderelection will happen for every service"
time="2023-09-24T01:23:38Z" level=info msg="starting services watcher for all namespaces"
time="2023-09-24T01:23:38Z" level=info msg="[endpoint] watching for service [nginx-controller] in namespace [ingress-nginx]"
time="2023-09-24T01:28:00Z" level=info msg="service [ingress-nginx/nginx-controller] has been deleted"
time="2023-09-24T01:28:00Z" level=info msg="[endpoints] stopping watching for [nginx-controller] in namespace [ingress-nginx]"
time="2023-09-24T01:28:03Z" level=info msg="[endpoint] watching for service [nginx-controller] in namespace [ingress-nginx]"
```

Logs are 100% identical in all daemonset pods.
In this test I tried re-deploying the the service.
I also tested this on both v0.6.2 and v0.5.12, and I got identical results.

It seems like the source of this message is here;
https://github.com/kube-vip/kube-vip/blob/cc96d65b14f40b5e127d996afc2dbc193d04bdb8/pkg/manager/watch_endpoints.go#L20

It looks to me like kube-vip can't find any local endpoints for some reason.

If I deploy with `externalTrafficPolicy: Cluster`, and then change it to Local, everything seems to be working.
If I deploy with `externalTrafficPolicy: Local`, and then change it to Cluster, external IP is still stuck in pending.

**Comment by thebsdbox** [comment] 2023-09-29 15:05
Could you tell me what the node names are, there appears to be a funny thing between short names and FQDN.. so getting the hostname and comparing it to the nodename on the endpoint can break,

**Comment by d-uzlov** [comment] 2023-09-29 18:46
Yeah, I created 3 clusters with different host name and node name, and it seems like the issue is indeed caused by node names:
- `hostname == mt3`, `hostname --fqdn == mt3`, `node name == mt3` works without issues
- `hostname == mt3`, `hostname --fqdn == mt3.domain.local`, `node name == mt3` works without issues
- `hostname == mt3`, `hostname --fqdn == mt3.domain.local`, `node name == mt3.domain.local` breaks

I would guess that kube-vip compares node name to output of `hostname`?
If so, I think this is incorrect behaviour, because I believe k8s doesn't impose any limits on node names, so it doesn't have to match neither `hostname`, nor `hostname --fqdn` value.

**Comment by thebsdbox** [comment] 2023-10-24 12:52
This is now fixed in the latest release, where FQDNs are used!

**Closed by thebsdbox** 2023-10-24 12:52 UTC
