### ISSUE TITLE
Additional loadbalanced controlplane ports

### ISSUE THREAD

**Issue by jnummelin** [kube-vip/kube-vip#744] opened 2024-01-30 20:59 UTC
**Is your feature request related to a problem? Please describe.**

In some cases the control planes need to expose additional ports. In the case of [k0s](https://github.com/k0sproject/k0s) there needs to be additional ports 8132 and 9443 that are loadbalanced on the controlplane nodes.

**Describe the solution you'd like**

Have some configuration option to define additional ports to control plane LB. Maybe something like:
```
--additional-cp-ports=8132:8132,9443:9443
```

the `source:target` format would allow easy mapping capability for users.

In the actual implementation this would behave pretty much like the existing 6443 port functionality. Except for other set of ports of course. 😄 

**Describe alternatives you've considered**

Some folks mitigate this combining kube-vip with HAProxy or similar. Not ideal as it requires more resources and stuff to configure.

**Additional context**

**Comment by ssurenr** [comment] 2024-09-22 20:41
@jnummelin Looks like you can pass `--port` argument multiple times. For example, for an RKE2 cluster I passed the argument in the generated config like this:
```yaml
spec:
  template:
    spec:
      containers:
      - args:
        - manager
        - --port=6443
        - --port=9345
        env:
        - name: vip_arp
          value: "true"
```

**Comment by Cellebyte** [comment] 2024-11-06 09:10
Probably could be achieved also when request #464 is implemented.

**Comment by Cellebyte** [comment] 2024-11-06 09:11
Duplicate of #464

**Closed by Cellebyte** 2024-11-06 09:11 UTC

**Comment by maxisam** [comment] 2024-12-19 21:44
> @jnummelin Looks like you can pass `--port` argument multiple times. For example, for an RKE2 cluster I passed the argument in the generated config like this:
> 
> ```yaml
> spec:
>   template:
>     spec:
>       containers:
>       - args:
>         - manager
>         - --port=6443
>         - --port=9345
>         env:
>         - name: vip_arp
>           value: "true"
> ```

Are you sure it works? somehow it doesn't work for me.
I used `sudo ipvsadm -L -n` to check this but I still only see port 6443
