### ISSUE TITLE
Bug with 0.3.4 and 0.3.5 "Kube-Vip is waiting for annotations to be present on this node"

### ISSUE THREAD

**Issue by tabdulazim** [kube-vip/kube-vip#226] opened 2021-07-03 00:52 UTC
**Describe the bug**

Kubevip version `0.3.4` and `0.3.5` does not recognize Equinix Metal CCM annotations

**To Reproduce**
```shell
export CCM_VERSION=3.1.0
export KUBEVIP_VERSION=0.3.5

export API_TOKEN=<???>
export PROJECT_ID=<???>

kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: metal-cloud-config
  namespace: kube-system
stringData:
  cloud-sa.json: |
    {
      "apiKey": "${API_TOKEN}",
      "projectID": "${PROJECT_ID}",
      "loadbalancer": "kube-vip://"
    }
EOF

kubectl apply -f equinix-secret-config.yaml

kubectl apply -f https://github.com/equinix/cloud-provider-equinix-metal/releases/download/v${CCM_VERSION}/deployment.yaml

kubectl apply -f https://kube-vip.io/manifests/rbac.yaml

alias kube-vip="docker run --network host --rm plndr/kube-vip:${KUBEVIP_VERSION}"

kube-vip manifest daemonset  \
  --interface lo \
  --services  \
  --bgp  \
  --annotations metal.equinix.com  \
  --inCluster | kubectl apply -f -
  
```

**Expected behavior**
IP allocation to `LoadBalancer` services but instead the message "Kube-Vip is waiting for annotations to be present on this node" appears in `kubevip` logs

**Note**: using version 0.3.3 works as expected

**Environment (please complete the following information):**
 - OS/Distro: Debian Buster
 - Kubernetes Version: 1.21.2
 - Kube-vip Version: 0.3.5

**Additional context**
The bug is confirmed by Equinix Metal team

**Comment by thebsdbox** [comment] 2021-07-05 10:30
Confirmed this... 
```
root@k8s:~# k logs -n kube-system   kube-vip-ds-wcv2n
time="2021-07-05T10:29:10Z" level=info msg="server started"
time="2021-07-05T10:29:10Z" level=info msg="Kube-Vip is waiting for annotations to be present on this node"
```

Investigating.

**Comment by thebsdbox** [comment] 2021-07-05 12:31
Well that was irritating! The bug was due to the watcher waiting for a password annotation, if no BGP password is enabled it will be stuck waiting for one.

**Comment by tabdulazim** [comment] 2021-07-05 17:17
Excellent, thanks a lot @thebsdbox for the quick fix!

**Comment by flokli** [comment] 2021-07-14 16:04
As written in https://github.com/kube-vip/kube-vip/pull/227#issuecomment-880002021, once this has landed in a release, this can probably be closed.

**Comment by thebsdbox** [comment] 2021-07-16 14:31
New release 0.3.6 has this fix !

**Closed by thebsdbox** 2021-07-16 14:31 UTC
Labels: bug

**Comment by tabdulazim** [comment] 2021-07-16 16:08
Thanks @thebsdbox, the fix works, there is a tiny issue

The generated daemonset from the command below, still has `image: plndr/kube-vip:v0.3.5`, when I manually fix the image tag, it works fine.

```
docker run --network host --rm docker.io/plndr/kube-vip:v0.3.6 manifest daemonset \
    --interface lo \
    --services \
    --bgp \
    --annotations metal.equinix.com \
    --inCluster
```

**Comment by thebsdbox** [comment] 2021-07-16 16:24
Nooooo.. I forgot to update the `Makefile`

**Comment by flokli** [comment] 2021-07-18 05:51
Will there be a 0.3.7 with the right version pointers everywhere?
